/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.ncdt.ui;

import com.google.inject.Injector;
import org.eclipse.ncdt.gcode.ui.internal.GcodeActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GCodeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GcodeActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GcodeActivator.getInstance().getInjector(GcodeActivator.ORG_ECLIPSE_NCDT_GCODE);
	}
	
}
