/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.ncdt.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGCodeScopeProvider extends DelegatingScopeProvider {
}
