/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.ncdt


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GCodeRuntimeModule extends AbstractGCodeRuntimeModule {
}
