/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.ncdt


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GCodeStandaloneSetup extends GCodeStandaloneSetupGenerated {

	def static void doSetup() {
		new GCodeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
