/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.ncdt.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.ncdt.parser.antlr.internal.InternalGCodeParser;
import org.eclipse.ncdt.services.GCodeGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GCodeParser extends AbstractAntlrParser {

	@Inject
	private GCodeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGCodeParser createParser(XtextTokenStream stream) {
		return new InternalGCodeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public GCodeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GCodeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
