/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.ncdt.gCode.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.ncdt.gCode.GBlock;
import org.eclipse.ncdt.gCode.GCodePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>GBlock</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GBlockImpl extends BlockImpl implements GBlock
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GBlockImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GCodePackage.Literals.GBLOCK;
  }

} //GBlockImpl
