/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.ncdt.gCode.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.ncdt.gCode.GCodePackage;
import org.eclipse.ncdt.gCode.MBlock;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>MBlock</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MBlockImpl extends BlockImpl implements MBlock
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MBlockImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GCodePackage.Literals.MBLOCK;
  }

} //MBlockImpl
