/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.ncdt.gCode;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MBlock</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.ncdt.gCode.GCodePackage#getMBlock()
 * @model
 * @generated
 */
public interface MBlock extends Block
{
} // MBlock
